services:
  ui:
    labels:
      - "traefik.http.routers.registro-ui.rule=Host(`${FQDN_REGISTRO:-registro-docker.test}`)"
      - "traefik.http.routers.registro-ui.entrypoints=websecure"
      - "traefik.http.routers.registro-ui.tls=true"

networks:
  default:
    name: ${NETWORK_NAME:-traefik-network}
    external: true
